# Generated by Django 3.1 on 2020-08-17 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='todolist',
            new_name='TaskList',
        ),
    ]
